// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcwscwjwemuhdnjsznwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjd3Njd2p3ZW11aGRuanN6bndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTU0MDgsImV4cCI6MjA2MzU3MTQwOH0.SoOCRVVO3e4APXiGy49Tp_uFliyg2CJGHYEH7gq3jTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);